"""add_user_roles_to_spaces

Revision ID: b10a7ec0b953
Revises: 3a712a139128
Create Date: 2025-09-03 16:38:16.857926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b10a7ec0b953'
down_revision: Union[str, Sequence[str], None] = '3a712a139128'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('users_in_spaces', 'is_creator',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users_in_spaces', 'role',
               existing_type=postgresql.ENUM('ADMIN', 'PARTICIPANT', 'VISITOR', name='userrole'),
               nullable=True)
    op.alter_column('users_in_spaces', 'joined_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_index(op.f('ix_users_in_spaces_id'), table_name='users_in_spaces')
    op.drop_constraint(op.f('unique_user_space'), 'users_in_spaces', type_='unique')
    op.drop_column('users_in_spaces', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_in_spaces', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.create_unique_constraint(op.f('unique_user_space'), 'users_in_spaces', ['user_id', 'space_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_users_in_spaces_id'), 'users_in_spaces', ['id'], unique=False)
    op.alter_column('users_in_spaces', 'joined_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('users_in_spaces', 'role',
               existing_type=postgresql.ENUM('ADMIN', 'PARTICIPANT', 'VISITOR', name='userrole'),
               nullable=False)
    op.alter_column('users_in_spaces', 'is_creator',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    # ### end Alembic commands ###
