"""Add is_creator field to users_in_spaces

Revision ID: fa240f93b5ae
Revises: 16c1b7538dd8
Create Date: 2025-08-20 23:16:41.923525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fa240f93b5ae'
down_revision: Union[str, Sequence[str], None] = '16c1b7538dd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_in_spaces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('space_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'PARTICIPANT', 'VISITOR', name='userrole'), nullable=False),
    sa.Column('is_creator', sa.Boolean(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['space_id'], ['spaces.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'space_id', name='unique_user_space')
    )
    op.create_index(op.f('ix_users_in_spaces_id'), 'users_in_spaces', ['id'], unique=False)
    op.drop_index(op.f('ix_users_in_space0s_id'), table_name='users_in_space0s')
    op.drop_table('users_in_space0s')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_in_space0s',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('space_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('role', postgresql.ENUM('ADMIN', 'PARTICIPANT', 'VISITOR', name='userrole'), autoincrement=False, nullable=False),
    sa.Column('is_creator', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('joined_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['space_id'], ['spaces.id'], name=op.f('users_in_space0s_space_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('users_in_space0s_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('users_in_space0s_pkey')),
    sa.UniqueConstraint('user_id', 'space_id', name=op.f('unique_user_space'))
    )
    op.create_index(op.f('ix_users_in_space0s_id'), 'users_in_space0s', ['id'], unique=False)
    op.drop_index(op.f('ix_users_in_spaces_id'), table_name='users_in_spaces')
    op.drop_table('users_in_spaces')
    # ### end Alembic commands ###
